### ISSUE TITLE
Modals Broken On Latest KSL Header

### ISSUE THREAD

**Issue by ssagers** [deseretdigital-ui/ddm-modal#2]
With the latest version of the KSL Header (where the page scrolling was changed), the modals have issues.  The modal and the gray overlay now scroll with the rest of the content.
Suggested fix:  There is a position: absolute; on .ksl-assets-modal which when switched to position: fixed; appears to keep the overlay and modal in the correct position.  Even with that suggested fix the background content still scrolls.

**Comment by jehoshua02** [comment]
I would refactor the modal to not rely on `.ddm-menu-container` classes and just used fixed positioning.

**Comment by jehoshua02** [comment]
Fixed in [1.1.0](https://github.com/deseretdigital-ui/ddm-modal/releases/tag/v1.1.0)
